config/routes.rb
Rails.application.routes.draw do

  root to: 'application#welcome'

  #signup
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'

  #logging in
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy' 

  #fb omniauth logging in
  get '/auth/facebook/callback' => 'sessions#omniauth'

  resources :runs do 
    resources :reviews, only: [:show, :new, :create, :edit, :update, :destroy]
  end 
  resources :reviews, only: [:index]

  resources :users, only: [:new, :create, :show] do 
    resources :runs, only: [:index]
  end 


  
  #gem or api, submit a photo review a run, nested form run&review at same time
  #would like to collection select for terrain, and also put limit on rating numbers
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/review.rb
class Review < ApplicationRecord
    belongs_to :user
    #required: false #https://stackoverflow.com/questions/39359168/rails-nested-form-error-child-must-exist
    belongs_to :run

    validates :title, :review_race_name, :description, :rating, presence: true

    scope :highest_rating, -> { order(rating: :desc) }
end

app/models/run.rb
class Run < ApplicationRecord
    belongs_to :user #now we have @run.user
    #https://github.com/rails/rails/issues/25198 
    #https://api.rubyonrails.org/classes/ActiveRecord/Associations/ClassMethods.html#method-i-has_many
    #i am confused where to put the inverse
    has_many :reviews
    #, inverse_of: :run
    has_many :users, through: :reviews 
    #accepts_nested_attributes_for :reviews

    validates :run_race_name, :terrain, :location_city, :location_state, :month, presence: true 
    validates :run_race_name, uniqueness: true 
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password

    has_many :reviews
    has_many :runs, through: :reviews

    validates :email, presence: true, uniqueness: true 

    def self.from_omniauth(auth)
      @user = User.find_or_create_by(email: auth["info"]["email"]) do |user|
        user.password = SecureRandom.hex
      end
    end 

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    helper_method :current_user
    helper_method :user_signed_in?

    def welcome
    end 

    def redirect_if_not_logged_in
        if !user_signed_in?
            redirect_to '/'
        end 
    end

    def current_user 
        @current_user ||= User.find_by(id: session[:user_id])
    end 

    def user_signed_in?
        !!current_user
    end
    
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
    before_action :redirect_if_not_logged_in
    before_action :set_run_id, only: [:show, :create, :edit, :destroy]
    before_action :find_review, only: [:show, :create, :edit, :update, :destroy]

    def index 
        @reviews = Review.all
    end 

    def show
    end 

    def new
        #nested new route has access to run_id
        params[:run_id] && @run = Run.find_by_id(params[:run_id])
        @run = Run.find_by_id(params[:run_id])
        @review = @run.reviews.build
    end 

    def create
        @review = current_user.reviews.build(review_params)
        @review.user_id = current_user.id 
        @review.run_id = params[:run_id]
        if @review.save 
            flash[:success] = "Successfully created!"
            redirect_to run_review_path(@review.run_id, @review)
        else 
            render :new
        end 
    end 

    def edit 
    end

    def update 
        if @review.update(review_params)
            flash[:success] = "Successfully updated!"
            redirect_to run_review_path(@review.run_id, @review)
        else
            redirect_to '/'
        end
    end 

    def destroy
        @user = current_user
        @review.destroy
        redirect_to user_path(@user)
    end

    private

    def review_params
        params.require(:review).permit(:run_id, :user_id, :title, :review_race_name, :description, :rating)
    end 

    def set_run_id 
        @run = Run.find_by_id(params[:run_id])
    end 

    def find_review 
        @review = Review.find_by_id(params[:id])
    end 
end

app/controllers/runs_controller.rb
class RunsController < ApplicationController
    before_action :redirect_if_not_logged_in
    before_action :set_run, only: [:show, :edit, :update, :destroy]
    
    def index 
        if params[:user_id]
            
            @runs = Run.where({ user_id: params[:user_id]})
        #if there is a user_id set the view to show all of that users runs 
        else 
        @runs = Run.all
        end 
    end 

    def show
    end 

    def new
        params[:user_id] && @user = User.find_by_id(params[:user_id])
        @run = Run.new
        #@run.reviews.build
    end 

    def create
        @run = current_user.runs.build(run_params)
        @run.user_id = current_user.id 

        if @run.save 
            flash[:success] = "Successfully created!"
            redirect_to run_path(@run)
        else 
            render :new 
        end 
    end 

    def edit 
    
    end

    def update 
        @user = User.find_by_id(params[:id])
       
        if @run.update(run_params)
            flash[:success] = "Successfully updated!"
            redirect_to run_path 
        else 
            render :edit 
        end 
    end 

    def destroy
        @user = current_user
        @run.destroy
        redirect_to user_path(@user)
    end

    private

    def run_params
        params.require(:run).permit(:run_race_name, :terrain, :location_city, :location_state, :month, :user_id)
        # reviews_attributes: [
        #     :title, 
        #     :review_race_name, 
        #     :description, 
        #     :rating,
        #     ]
        # )
    end 

    def set_run
        @run = Run.find_by_id(params[:id])
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def home 
    end 

    def index 
    end 

    def show
    end 

    def new
    end 

    def create
        @user = User.find_by(email: params[:user][:email]) #params from login form 
 
            if @user && @user.authenticate(params[:user][:password])
                session[:user_id] = @user.id #save the user id inside browser cookies and login
                flash[:alert] = "Login successful!"
                redirect_to user_path(@user)
            else 
                flash[:alert] = "Please try again!"
                redirect_to '/login'
            end 
    end 

    def omniauth
        @user = User.from_omniauth(auth)
            @user = User.find_or_create_by(uid: auth['uid']) do |u|
            u.name = auth['info']['name']
            u.email = auth['info']['email']
            u.image = auth['info']['image']
                if @user.save 
                    session[:user_id] = @user.id 
                    redirect_to user_path(@user)
                else 
                    flash[:alert] = "Please try again!"
                    redirect_to '/login'
                end 
            end 
    end 

    #request.env
    #request.env['omniauth.auth']

    def edit 
    end

    def update 
    end 

    def destroy
        session.clear 
        redirect_to root_path
    end

    private 

    def auth
        request.env['omniauth.auth']
    end
end 

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def show
        @user = User.find_by_id(params[:id])
    end 

    def new
        @user = User.new 
    end 

    def create
        @user = User.new(user_params)
        if @user.save 
            session[:user_id] = @user.id 
            flash[:error] = "Your account has been created!"
            redirect_to @user #user show page 
        else 
            flash[:error] = "Please try again!"
            redirect_to '/signup'
        end 
    end 

    def edit 
    end

    def update 
    end 

    def destroy
    end

    private 

    def user_params
        params.require(:user).permit(:email, :password, :name, :image, :uid, :provider)
    end
end

#https://launchschool.com/blog/integrating-rails-and-bootstrap-part-2

app/helpers/application_helper.rb
module ApplicationHelper

    def flash_class(level)
        case level
            when :notice then "alert alert-info"
            when :success then "alert alert-success"
            when :error then "alert alert-error"
            when :alert then "alert alert-error"
        end
    end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/runs_helper.rb
module RunsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/application/welcome.html.erb
<br>
<br>
<br>
<h3 class="text-center"> Welcome to Marathon Reviews! </h3> 
<br>
<h5 class="text-center">

<!-- -->
 <button type="button", class="btn btn-outline-primary btn-lg">
<%= link_to('Login with Facebook', '/auth/facebook') %>
</button> 

<button type="button", class="btn btn-outline-primary btn-lg">
<a href="/signup">Signup with Email</a>
</button>
<button type="button", class="btn btn-outline-primary btn-lg">
<a href="/login">Login with Email</a>
</button>
</h5>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(object.errors.count, "error") %> prohibited this from being saved:</h2>

    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MarathonReview</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <%= render 'shared/navigation' %>

  <div id ="main-container" class="container">
    <div class="row">
      <div class="col-xs-12">
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, class: "alert alert-danger" %>
      <% end %>
      </div>
    </div>
    <div class="row">
      <div class="col-xs-3"></div>
      </div>
        <div class="col-xs-9">
        <%= yield %>
    </div>
  </div>
</div>

  </body>
</html>

app/views/reviews/_review.html.erb
<%= form_for [@run, @review] do |f| %>
    <div class="field form-group">
        <%= f.label :title, "Review Title: ", class: 'col-sm-2 control-label' %>
        <div class="col-sm-10">
            <%= f.text_field :title, class: 'form-control' %>
        </div>
    </div>
    
    <div class="field form-group">
        <%= f.label :review_race_name, "Marathon Name: ", class: 'col-sm-2 control-label' %>
        <div class="col-sm-10">
            <%= f.text_field :review_race_name, class: 'form-control' %>
        </div>
    </div>
    
    <div class="field form-group">
        <%= f.label :description, "Review Content: ", class: 'col-sm-2 control-label' %>
        <div class="col-sm-10">
            <%= f.text_field :description, class: 'form-control' %>
        </div>
    </div>
    
    <div class="field form-group">
        <%= f.label :rating, "Rating: ", class: 'col-sm-2 control-label' %>
        <div class="col-sm-10">
            <%= f.number_field :rating, class: 'form-control' %><br>
        </div>
    </div>

    <div class="actions form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <%= f.submit %>
        </div
    </div>
<% end %>

app/views/reviews/edit.html.erb
<%= render partial: "layouts/errors", locals: {object: @review} %>
<br>
<h3> Edit Review </h3>
<br>
<%= render partial: "review", locals: {review: @review} %>

app/views/reviews/index.html.erb
<br>
<h3 class="text-center">Reviews:</h3>
<br>
<h5 class="text-center">
<% @reviews.highest_rating.each do |r| %>
    <%= link_to r.title, run_review_path(r.run_id, r) %> <br>
    <%= r.review_race_name %><br>
    By: <%= r.user.email %><br>
    Rating: <%= r.rating %><br><br>
<% end %>
</h5>

app/views/reviews/new.html.erb
<%= render partial: "layouts/errors", locals: {object: @review} %>
<br>
<h3> New Review </h3>
<br>
<%= render partial: "review", locals: {review: @review} %>

app/views/reviews/show.html.erb
<br>
<h3 class="text-center">
<%= @review.review_race_name %> Review<br>
</h3>

<h5 class="text-center">
<%= "Title: " %><%= @review.title %><br>
<%= "Content: " %><%= @review.description %><br>
<%= "Rating: " %><%= @review.rating %><br>
By: <%= @review.user.email %>
<br>
<% if current_user.id == @review.user_id %>
    <button type="button" class="btn btn-outline-primary">
        <%= link_to "Edit Review", edit_run_review_path(@run, @review) %>
    </button>
    <button type="button" class="btn btn-outline-primary">
        <%= link_to "Delete Review", run_review_path(@run, @review), method: :delete %>
    </button>
<% end %>
</h5>

app/views/runs/_run.html.erb
<h4> Marathon: </h4>
<%= form_for(@run, html: {class: 'form-horizontal'}) do |f| %>

    <div class="field form-group">
        <%= f.label :run_race_name, "Marathon Name: ", class: 'col-sm-2 control-label' %>
        <div class="col-sm-6">
            <%= f.text_field :run_race_name, class: 'form-control' %>
        </div>
    </div>

    <div class="field form-group">
        <%= f.label :terrain, "Marathon Terrain: ", class: 'col-sm-2 control-label' %>
        <div class="col-sm-6">
            <%= f.select :terrain, ['road', 'beach'], class: 'form-control' %>
        </div>
    </div>

    <div class="field form-group">
        <%= f.label :location_city, "Marathon City: ", class: 'col-sm-2 control-label' %>
        <div class="col-sm-6">
            <%= f.text_field :location_city, class: 'form-control' %>
        </div>
    </div>

    <div class="field form-group">
        <%= f.label :location_state, "Marathon State: ", class: 'col-sm-2 control-label' %>
        <div class="col-sm-6">
            <%= f.text_field :location_state, class: 'form-control' %>
        </div>
    </div>

    <div class="field form-group">
        <%= f.label :month, "Month of Marathon: ", class: 'col-sm-2 control-label' %>
        <div class="col-sm-6">
            <%= f.text_field :month, class: 'form-control' %><br>
        </div>
    </div>

    <div class="actions form-group">
        <div class="col-sm-offset-2 col-sm-6">
            <%= f.submit %>
        </div
    </div>
<% end %>

app/views/runs/edit.html.erb
<%= render partial: "layouts/errors", locals: {object: @run} %>
<br>
<h3> Edit Race Form </h3>
<br>
<%= render 'run' %>

app/views/runs/index.html.erb
<br>
<h3 class="text-center"> Marathons:</h3>
<br>
<h5 class="text-center">

<% @runs.each do |run| %>
    <div><%= link_to run.run_race_name, run_path(run) %> </div>
    <div><%= run.location_city %>, <%= run.location_state %></div>
    <div>by: <%= run.user.email %></div><br>
<% end %>

</h5>

app/views/runs/new.html.erb
<%= render partial: "layouts/errors", locals: {object: @run} %>
<br>
<h3> New Marathon Form! </h3>
<br>
<%= render 'run' %>

app/views/runs/show.html.erb
<%= render partial: "layouts/errors", locals: {object: @run} %>
    <br>
<h2 class="text-center">
    <div> <%= @run.run_race_name %><div></h2>
<h5 class="text-center">
    <div> Race Terrain: <%= @run.terrain %><div>
    <div> Race City: <%= @run.location_city %><div>
    <div> Race State: <%= @run.location_state %><div>
    <div> Race Month: <%= @run.month %><div>
    <div> by: <%= @run.user.email %>
</h5>
    <br> </br>
<h4 class="text-center"> Marathon Reviews: </h4>
    <br></br>
    <div>
<h5 class="text-center">
<% @run.reviews.each do |review| %>
    <%= link_to "#{review.review_race_name}", run_review_path(@run, review) %><div>
    Rated <%= "#{review.rating}" %><div> <br></br>
    
<% end %>
    <br>
<% if current_user == @run.user %>
    <button type="button" class="btn btn-outline-primary">
        <%= link_to "Edit Marathon", edit_run_path(@run) %>
    </button>
    <button type="button" class="btn btn-outline-primary">
        <%= link_to "Delete Marathon", run_path(@run), method: :delete %>
    </button
<% end %>
<br>
<br><br>
<button type="button" class="btn btn-warning">
    <%= link_to "Add a Review for #{@run.run_race_name}", new_run_review_path(@run) %>
</button>
</h5>

app/views/shared/_navigation.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container">
    <div class="navbar-header">

    <% if !user_signed_in? %>
      <a class="navbar-brand" href="/"> Welcome Page </a>
    <% end %>
       
      <% if user_signed_in? %>
        <a class="navbar-brand" <%= link_to "Home", user_path(current_user) %></a>
        <a class="navbar-brand" <%= link_to "All Marathons", runs_path %></a>
        <a class="navbar-brand" <%= link_to "Add a Marathon", new_run_path %></a>
        <a class="navbar-brand" <%= link_to "All Reviews", reviews_path %></a>
        <a class="navbar-brand" <%= link_to "Logout", logout_path, method: :delete %></a>
      <% end %>

    </div>
  </div>
</nav>

app/views/users/new.html.erb
<%= render partial: "layouts/errors", locals: {object: @user} %>
<br>
<h3> Signup </h3>
<br>
<%= form_for :user do |f| %>
    <div class="field form-group">
        <div class="col-sm-6">
            <%= f.label :email, "Email: ", class: 'col-sm-2 control-label' %>
            <div class="col-sm-10">
            <%= f.text_field :email, class: 'form-control' %>
        </div>
    </div>
    <div class="field form-group">
        <div class="col-sm-6">
        <%= f.label :password, "Password: ", class: 'col-sm-2 control-label' %>
        <div class="col-sm-10">
        <%= f.password_field :password, class: 'form-control' %><br>
        </div>
    </div>
    <div class="actions form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <%= f.submit %>
        </div
    </div>
<% end %>

app/views/users/show.html.erb
<br>
<h3 class="text-center"> Welcome <%= @user.email %>! </h3> 
<br>
<h3 class="text-center">Your Reviews: </h3>
<div>
<h5 class="text-center">
<% @user.reviews.each do |r| %>
    <div><%= link_to r.review_race_name, run_review_path(r.run_id, r) %> <br></div>
    <%= r.title %><br>
    Rating: <%= r.rating %><br>
    by: <%= r.user.email %><br>
<% end %>
</h5>
<br><br>